const itemList = [
    {id: 1, key: "ice-burner-weapon", name: "神秘极光武器宝箱", rate: 0.3, highLight: true},
    {id: 2, key: "ice-burner-hair", name: "神秘极光发型宝箱", rate: 0.3, highLight: true},
    {id: 3, key: "ice-burner-another-hair", name: "神秘极光另一个发型宝箱", rate: 0.3, highLight: true},
    {id: 4, key: "ice-burner-top-piece", name: "神秘极光上衣宝箱", rate: 0.6, highLight: true},
    {id: 5, key: "ice-burner-bottom-piece", name: "神秘极光下衣宝箱", rate: 0.6, highLight: true},
    {id: 6, key: "ice-burner-gloves", name: "神秘极光手套宝箱", rate: 1.1, highLight: true},
    {id: 7, key: "ice-burner-shoes", name: "神秘极光鞋子宝箱", rate: 1.1, highLight: true},
    {id: 8, key: "ice-burner-accessory1", name: "神秘极光饰品（上衣）宝箱", rate: 0.35, highLight: true},
    {id: 9, key: "ice-burner-accessory2", name: "神秘极光饰品（项链）宝箱", rate: 0.35, highLight: true},
    {id: 10, key: "weapon-magic-amulent-9", name: "武器专用强化卷轴Lv.9", rate: 0.0299, midLight: true},
    {id: 11, key: "weapon-magic-amulent-10", name: "武器专用强化卷轴Lv.10", rate: 0.0001, midLight: true},
    {id: 12, key: "armo-magic-amulent-9", name: "防具专用强化卷轴Lv.9", rate: 0.0299, midLight: true},
    {id: 13, key: "armor-magic-amulent-10", name: "防具专用强化卷轴Lv.10", rate: 0.0001, midLight: true},
    {id: 14, key: "glory-of-victory", name: "胜利的荣光", rate: 0.3, midLight: true},
    {id: 15, key: "berserker", name: "狂战士", rate: 0.001, midLight: true},
    {id: 16, key: "sacrifice", name: "牺牲者", rate: 0.001, midLight: true},
    {id: 17, key: "magic-amulent-8", name: "强化卷轴Lv.8", rate: 2},

    {id: 18, key: "orichalcum-weapon-accessory", name: "奥利哈钢武器装饰宝箱", rate: 2},
    {id: 19, key: "promotional-costume", name: "晋级时装（7日）宝箱", rate: 2},
    {id: 20, key: "additional-damage-magic-stone", name: "追加伤害特级魔法石", rate: 1.5},
    {id: 21, key: "damage-reduction-stone", name: "减少伤害特级魔法石", rate: 1.5},
    {id: 22, key: "critical-magic-stone", name: "暴击特级魔法石", rate: 1.25},
    {id: 23, key: "maximize-magic-stone", name: "极大化特级魔法石", rate: 1.25},
    {id: 24, key: "action-speed-magic-stone", name: "动作速度特级魔法石", rate: 1.25},
    {id: 25, key: "HP-magic-stone", name: "HP增加特级魔法石", rate: 1.5},
    {id: 26, key: "elrianode-boss", name: "艾丽阿诺德BOSS宝箱", rate: 1.599},
    {id: 27, key: "varnimyr-boss", name: "帕尼米尔BOSS宝箱", rate: 0.099},
    {id: 28, key: "rigomor-boss", name: "尼格摩尔BOSS宝箱", rate: 0.099},
    {id: 29, key: "sage-magic-stone", name: "贤者的魔法石（2个）宝箱", rate: 0.5},

    {id: 30, key: "complete-recovery-100", name: "完全恢复药水（100个）宝箱", rate: 10},
    {id: 31, key: "complete-recovery-50", name: "完全恢复药水（50个）宝箱", rate: 4},
    {id: 32, key: "fighting-spirit", name: "斗志药水", rate: 1},
    {id: 33, key: "adaptation-elixir", name: "适应的灵药", rate: 1.79},
    {id: 34, key: "steel-spinning-reel", name: "钢铁钓轮", rate: 2},
    {id: 35, key: "colorful-bobber", name: "五颜六色的鱼漂", rate: 2},

    {id: 36, key: "el-shard-mystery", name: "艾尔结晶（未鉴定） 50个", rate: 4},
    {id: 37, key: "el-shard-fire", name: "艾尔结晶（火） 50个", rate: 4},
    {id: 38, key: "el-shard-water", name: "艾尔结晶（水） 50个", rate: 4},
    {id: 39, key: "el-shard-wind", name: "艾尔结晶（风） 50个", rate: 4},
    {id: 40, key: "el-shard-nature", name: "艾尔结晶（地） 50个", rate: 4},
    {id: 41, key: "el-shard-light", name: "艾尔结晶（光） 50个", rate: 4},
    {id: 42, key: "el-shard-dark", name: "艾尔结晶（暗） 50个", rate: 4},
    {id: 43, key: "fire-orbs-fire", name: "火之水晶球（250个）宝箱", rate: 2},
    {id: 44, key: "fire-orbs-water", name: "水之水晶球（250个）宝箱", rate: 2},
    {id: 45, key: "fire-orbs-wind", name: "风之水晶球（250个）宝箱", rate: 2},
    {id: 46, key: "fire-orbs-nature", name: "地之水晶球（250个）宝箱", rate: 2},
    {id: 47, key: "fire-orbs-light", name: "光之水晶球（250个）宝箱", rate: 2},
    {id: 48, key: "fire-orbs-dark", name: "暗之水晶球（250个）宝箱", rate: 2},
    {id: 49, key: "ruben-boss", name: "摩奇BOSS宝箱", rate: 1.7},
    {id: 50, key: "elder-boss", name: "艾德BOSS宝箱", rate: 1.7},
    {id: 51, key: "bethma-boss", name: "贝斯马BOSS宝箱", rate: 1.7},
    {id: 52, key: "altera-boss", name: "厄泰拉BOSS宝箱", rate: 1.7},
    {id: 53, key: "feita-boss", name: "沛塔BOSS宝箱", rate: 1.7},
    {id: 54, key: "velder-boss", name: "拜德BOSS宝箱", rate: 1.7},
    {id: 55, key: "hamel-boss", name: "哈梅尔BOSS宝箱", rate: 1.7},
    {id: 56, key: "sander-boss", name: "桑德斯BOSS宝箱", rate: 1.7},
    {id: 57, key: "lanox-boss", name: "拉诺斯BOSS宝箱", rate: 2},
    {id: 58, key: "elysion-boss", name: "艾丽西昂BOSS宝箱", rate: 2}
]

const imageMap = {
    "ice-burner-weapon": '../../assets/aurora-mystica-cube.png',
    "ice-burner-hair": '../../assets/aurora-mystica-cube.png',
    "ice-burner-another-hair": '../../assets/aurora-mystica-cube.png',
    "ice-burner-top-piece": '../../assets/aurora-mystica-cube.png',
    "ice-burner-bottom-piece": '../../assets/aurora-mystica-cube.png',
    "ice-burner-gloves": '../../assets/aurora-mystica-cube.png',
    "ice-burner-shoes": '../../assets/aurora-mystica-cube.png',
    "ice-burner-accessory1": '../../assets/aurora-mystica-cube.png',
    "ice-burner-accessory2": '../../assets/aurora-mystica-cube.png',
    "weapon-magic-amulent-9": '../../assets/magic-amulent-9.png',
    "weapon-magic-amulent-10": '../../assets/magic-amulent-10.png',
    "armor-magic-amulent-9": '../../assets/magic-amulent-9.png',
    "armor-magic-amulent-10": '../../assets/magic-amulent-10.png',
    "magic-amulent-8": '../../assets/magic-amulent-8.png',
    // "glory-of-victory": {name: `胜利的荣光`},
    "berserker": '../../assets/berserker.png',
    "sacrifice": '../../assets/sacrifice.png',

    "orichalcum-weapon-accessory": '../../assets/orichalcum-weapon-accessory.png',
    "promotional-costume": '../../assets/promotional-costume.png',
    // "additional-damage-magic-stone": {name: `追加伤害特级魔法石`,},
    // "damage-reduction-stone": {name: `减少伤害特级魔法石`},
    // "critical-magic-stone": {name: `暴击特级魔法石`},
    // "maximize-magic-stone": {name: `极大化特级魔法石`},
    // "action-speed-magic-stone": {name: `动作速度特级魔法石`},
    // "HP-magic-stone": {name: `HP增加特级魔法石`},
    // "elrianode-boss": {name: `艾丽阿诺德BOSS宝箱`},
    // "varnimyr-boss": {name: `帕尼米尔BOSS宝箱`},
    // "rigomor-boss": {name: `尼格摩尔BOSS宝箱`},
    // "sage-magic-stone": {name: `贤者的魔法石（2个）宝箱`},

    "complete-recovery-100": '../../assets/complete-recovery.png',
    "complete-recovery-50": '../../assets/complete-recovery.png',
    // "fighting-spirit": {name: `斗志药水`},
    // "adaptation-elixir": {name: `适应的灵药`},
    // "steel-spinning-reel": {name: `钢铁钓轮`},
    // "colorful-bobber": {name: `五颜六色的鱼漂`},

    "el-shard-mystery": '../../assets/el-shard-mystery.png',
    "el-shard-fire": '../../assets/el-shard-fire.png',
    "el-shard-water": '../../assets/el-shard-water.png',
    "el-shard-wind": '../../assets/el-shard-wind.png',
    "el-shard-nature": '../../assets/el-shard-nature.png',
    "el-shard-light": '../../assets/el-shard-light.png',
    "el-shard-dark": '../../assets/el-shard-dark.png',
    "fire-orbs-fire": '../../assets/fire-orbs-fire.png',
    "fire-orbs-water": '../../assets/fire-orbs-water.png',
    "fire-orbs-wind": '../../assets/fire-orbs-wind.png',
    "fire-orbs-nature": '../../assets/fire-orbs-nature.png',
    "fire-orbs-light": '../../assets/fire-orbs-light.png',
    "fire-orbs-dark": '../../assets/fire-orbs-dark.png',
    "ruben-boss": '../../assets/ruben-boss.png',
    "elder-boss": '../../assets/elder-boss.png',
    "bethma-boss": '../../assets/bethma-boss.png',
    "altera-boss": '../../assets/altera-boss.png',
    "feita-boss": '../../assets/feita-boss.png',
    "velder-boss": '../../assets/velder-boss.png',
    "hamel-boss": '../../assets/hamel-boss.png',
    "sander-boss": '../../assets/sander-boss.png',
    "lanox-boss": '../../assets/lanox-boss.png',
    "elysion-boss": '../../assets/elysion-boss.png',
}

export { itemList, imageMap }